### ISSUE TITLE
Define where video-raf fires within the event loop processing model

### ISSUE THREAD

**Issue by tguilbert-google** [WICG/video-rvfc#1]
Other AnimationFrameProviders have defined times at which they are fired within the event loop processing model:
https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model

This issue tracks defining when video-raf callbacks should be fired within that model.

**Comment by tguilbert-google** [comment]
video.rAF callbacks will be fired as part of the "[update the rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering)" steps of the event loop processing model. For now, they are fired immediately before window.rAF callbacks (between step 10 and step 11 of the rendering steps).

Other than achieving parity with window.rAF's behavior, running as part of the rendering steps has some advantages over the other alternatives considered.

If the callbacks were run as tasks, we would have been at the mercy of an overloaded task queue. Callbacks queued at an appropriate time might be run after the frame has been displayed. Requeue-ing callbacks from within video.rAF wouldn't offer a reliable frame rate, because a heavy load on the main thread would delay the painting and re-registering of callbacks.

The callbacks could have been run as microtasks. However, if one were to paint frames from within the callback, and there were multiple frames presented between 2 v-sync, only the last one would be displayed, and the work done in the other callbacks would be wasted.

Running as part of the rendering steps gives us the guarantee that video.rAF callbacks will be called regularly, but no more than necessary. Delaying the callbacks to be v-sync aligned also maximizes the chances that we have the latest metadata for analysis and latest frame for painting.

**Comment by foolip** [comment]
I think this issue now amounts to invoking the algorithm in https://wicg.github.io/video-raf/#video-raf-procedures from somewhere in HTML.

**Comment by tguilbert-google** [comment]
The spec now defines from where in the HTML spec the procedure should be invoked.

Should I open an issue in the HTML github to track updating the HTML spec? Is it too early for a pull request?

**Comment by tguilbert-google** [comment]
I sent a pull request:
https://github.com/whatwg/html/pull/5332

I don't think it will be accepted until there is an official position from Safari or Firefox.

**Comment by tguilbert-google** [comment]
[The guidance](https://github.com/whatwg/html/pull/5332#issuecomment-594184703) is to move this spec into the HTML spec, since it changes the HTMLVideoElement.

For now, I am keeping this spec as-is and separate, until it graduates incubation.
