### ISSUE TITLE
List of animation frame callbacks is never used to invoke callbacks

### ISSUE THREAD

**Issue by foolip** [WICG/video-rvfc#10]
https://wicg.github.io/video-raf/#list-of-animation-frame-callbacks

This list is appended to in `requestAnimationFrame`, but nothing outside of `cancelAnimationFrame`, nothing looks at this list or invokes any of the callbacks.

**Comment by tguilbert-google** [comment]
I added the procedure that uses it. I have also added an issue about how to schedule that procedure, which I'm not really sure how to write in spec form.

**Comment by foolip** [comment]
Thanks! Looks like https://github.com/WICG/video-raf/issues/1 covers what's left to do here.
