### ISSUE TITLE
Test as much of VideoFrameMetadata members as possible

### ISSUE THREAD

**Issue by foolip** [WICG/video-rvfc#34]
It looks like https://github.com/web-platform-tests/wpt/tree/master/video-raf doesn't test the required attributes `presentationTime` and `expectedPresentationTime`. For both, one could assert that they're an own property of the metadata object, and also something about how they change one frame to the next, increasing rather than decreasing.

For the remaining optional dictionary arguments, one can have a test for each where it is expected to be present if the browser supports it at all, and use `assert_precondition` to (effectively) skip the test if it's not present. But if the precondition passes, one can make similar assertions as for required members.

(Like https://github.com/WICG/video-raf/issues/30 this should arguably be an issue in https://github.com/web-platform-tests/wpt/labels/video-raf but it's too hard to track issues in such a big repo.)

**Comment by tguilbert-google** [comment]
I will be adding updated WPTs as soon as the renames land.

**Comment by tguilbert-google** [comment]
This PR covers all parameters except processingDuration, which is truly optional.

https://github.com/web-platform-tests/wpt/pull/22951
