### ISSUE TITLE
Define when optional VideoFrameMetadata members should/must be present

### ISSUE THREAD

**Issue by foolip** [WICG/video-rvfc#35]
These members are optional because they're not always present, but there may still be conditions where they are that can be spelled out with normative language. It would be good to do one of these for each of them, in order of goodness
- spell out with a "must" or "should" when it's present
- spell out any conditions where it shouldn't be present, or say it's *only* present per the must/should conditions.
- give a non-normative note with a hint and a nudge about what's expected but for some reason isn't a good idea to make a normative requirement.

This might help make tests suggested in https://github.com/WICG/video-raf/issues/34 more stringent.

Taking `rtpTimestamp` as the example, one could then assert it's missing in a normal video playback case, that it is present in a WebRTC case, and that it's value is something in the range of what's possible.

**Comment by tguilbert-google** [comment]
Fixed in #45
