### ISSUE TITLE
What is the unit of width and height?

### ISSUE THREAD

**Issue by foolip** [WICG/video-rvfc#4]
https://wicg.github.io/video-raf/#video-frame-metadata-attributes doesn't give a unit for width and height.

Is it the same as `video.videoWidth` and `video.videoHeight` which is CSS pixels after applying aspect ratio adjustment?

**Comment by tguilbert-google** [comment]
`video.videoWidth` and `video.videoHeight` are backed by `VideoFrame::natural_size()`, while `width` and `height` are backed by `VideoFrame::visible_rect()`.

@dalecurtis does "raw pixels" as a unit seem correct?

**Comment by dalecurtis** [comment]
I'm not familiar with the details of "raw pixels", but if it's what's on the label, then yes that sounds correct. It's the exact number of ARGB/YUV pixels in the frame.

**Comment by tguilbert-google** [comment]
I picked up "raw pixels" from the MDN description of "[intrinsic pixels](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoHeight#About_intrinsic_width_and_height)", but that isn't necessarily normative.

**Comment by foolip** [comment]
Since the unit isn't the same as `videoWidth` and `videoHeight` this would need careful definition. From the name `VideoFrame::visible_rect()` it sounds like it's after "internal" cropping, and maybe the only difference to `videoWidth` and `videoHeight` is that aspect ratio hasn't been applied?

**Comment by dalecurtis** [comment]
It's probably worth understanding if we actually need these to be different. It was primarily added for WebGL and texImage and is what the existing WebGLVideoTexture has been using. So might be worth double checking with kbr/kainino to see what's most desired here.

**Comment by tguilbert-google** [comment]
I reached out to kbr/kainino. Ken said that using natural_size() wouldn't work for WebGL.

I am going to leave the implementation as is and better define the units.

**Comment by tguilbert-google** [comment]
I uploaded a tentative definition of "media pixels".

**Comment by foolip** [comment]
How will a web developer use this information?

**Comment by tguilbert-google** [comment]
I think the width/height should be used by a web developer when calling canvas.drawImage() and WebGLRenderingContext.texImage2d(). I tried simplifying "media pixel" definition (notably removing the "internal cropping").

I've tried to come up with a useful example where width/height is different than videoWidth/videoHeight. I don't know where we apply aspect ratios, or when natural_size() would be different than visible_rect(). Dale, do you have any suggestions?

**Comment by dalecurtis** [comment]
Here's where we do that computation:
https://source.chromium.org/chromium/chromium/src/+/master:media/base/video_util.cc;l=60

**Comment by tguilbert-google** [comment]
Thanks! That helped a lot (specifically knowing that an anamorphic video can have rectangular pixels)

I'm closing this issue, please re-open it if something else needs to be clarified.
