### ISSUE TITLE
mediaTime and current-playback-position

### ISSUE THREAD

**Issue by gabe97330** [WICG/video-rvfc#54]
The rvfc spec refers to video.currentTime in the definition of [mediaTime](https://wicg.github.io/video-rvfc/#dom-videoframemetadata-mediatime). The HTML spec refers to the "frame at [current playback position](https://html.spec.whatwg.org/multipage/media.html#current-playback-position)" when describing video as a source for drawImage in [canvas image sources](https://html.spec.whatwg.org/multipage/canvas.html#image-sources-for-2d-rendering-contexts). 

If mediaTime is  equivalent to current playback position would it make sense to refer to it directly?

**Comment by tguilbert-google** [comment]
From running a simple test, in practice there is a small difference between the two. However, they are both in the same time domain.

In Chromium's implementation, we use the audio clock as the time source that backs `video.currentTime`, whereas the `mediaTime` is directly populated by the presentationTimestamp of the frame.

Here's the result of dumping both values to the console, for the same video, on two different executions:

```
currentTime: 2.959645 mediaTime: 2.95
currentTime: 2.975929 mediaTime: 2.966667
currentTime: 3.009594 mediaTime: 3
```

```
currentTime: 2.950029 mediaTime: 2.95
currentTime: 2.952037 mediaTime: 2.966667
currentTime: 2.985389 mediaTime: 3
```

So, the `mediaTime` is what you should use if you wanted to exactly identify frames in a reproducible way, including to identify exactly which frames you missed (this is a 60fps video and both of those executions missed the `2.98333` frame, which can happen. I think my remote setup is running at 50hz though)

**Comment by gabe97330** [comment]
Great, thanks for the explanation. Closing the issue...
