### ISSUE TITLE
`requestVideoFrameCallback` does not work during a WebXR session

### ISSUE THREAD

**Issue by cabanier** [WICG/video-rvfc#58]
The [WebXR spec](https://immersive-web.github.io/webxr/) defines the following:

> An active immersive session MAY affect the rendering opportunity of a browsing context if it causes the page to be obscured

On devices that use the same display for the browser and the immersive session (ie standalone headset and phones), this will causes their regular rAF callbacks to stop firing during an immersive experience.
Because of this, the`requestVideoFrameCallback` will no longer fire even though the video itself is still playing. Many WebXR experiences use video and this feature would allow for much more efficient processing.

How can we change the spec so this callback fires while in immersive mode?

**Comment by dalecurtis** [comment]
Does this actually happen right now in Chrome? For offscreen video rVFC should continue to fire and thus trigger rAF generation as well IIRC.

**Comment by cabanier** [comment]
yes, see https://bugs.chromium.org/p/chromium/issues/detail?id=1107578

**Comment by tguilbert-google** [comment]
Hello! Sorry, I've been working heads down on WebCodecs for the past few weeks. I will be able to start work on this by EOW. Thank you for raising this issue!

**Comment by tguilbert-google** [comment]
Fixed as of Chromium 87.0.4280.0

See [crbug.com/1107578](https://crbug.com/1107578)
