### ISSUE TITLE
Add Security and Privacy section

### ISSUE THREAD

**Issue by foolip** [WICG/video-rvfc#6]
The spec makes available a bunch of new timing information. Are there any implications of this that implementors should be aware of?

**Comment by tguilbert-google** [comment]
I reached out to chrome-security-reviews and chrome-security-owp to see if there was anything else that should be called out.

**Comment by tguilbert-google** [comment]
I added more information. I don't foresee major changes in this section. I am closing this issue out, and will track specific details about the section in their own issues.
