### ISSUE TITLE
What can this API do in practice?

### ISSUE THREAD

**Issue by lincolnneu** [WICG/video-rvfc#63]
People who are interested in this API usually care about frame accuracy. But this API actually cannot guarantee that. Everything is *best effort*. It's not guaranteed to be called every frame is painted. There could be 1 v-sync late, and we need to know refresh rate of monitor in advance, which seems to be not easy to determine from javascript in general. Though `mediaTime is what you should use if you wanted to exactly identify frames in a reproducible way`, but how can it be reproducible if we are not guaranteed the mediaTime matches the frame being displayed?

references:
https://github.com/WICG/video-rvfc/issues/59
https://github.com/WICG/video-rvfc/issues/62

**Comment by dalecurtis** [comment]
As you say this API is best effort and tests show it works pretty well, hitting the vast majority of frames (see #3). The mediaTime will tell you either the frame is about to be displayed or is already on the screen. For use cases that don't explicitly require 100% of the frames to be captured (frame metrics analysis, duplicating the video frame with effects, etc) this is fine.

If you actually need 100% frame accuracy you'll need an API like [WebCodecs](https://github.com/WICG/web-codecs/blob/master/explainer.md) where you can decode and display each frame individually. While this may still suffer from dropped frames at the OS level, at least you'll have 100% consistent in page knowledge of what's on the screen.
