### ISSUE TITLE
Does this API has limitation to B frames in chrome?

### ISSUE THREAD

**Issue by lincolnneu** [WICG/video-rvfc#64]
There's a decade old chrome bug that video frame displayed does not match currentTime when there's B frame in the video:
https://bugs.chromium.org/p/chromium/issues/detail?id=66631 . Is this API independent to this bug?

**Comment by dalecurtis** [comment]
video.rVFC is unaffected by that bug. That bug is specifically due to a long standing ffmpeg bug where seeking doesn't work as expected in files with b-frames. This API tells you what frame was sent to the compositor, so seeking can't impact it.

**Comment by lincolnneu** [comment]
If requestVideoFrameCallback is fired for a B frame, and then we seek to its pts time according to metadata.mediaTime using `videoNode.currentTime = metadata.mediaTime`, is it guaranteed to show that frame correctly?

metadata.mediaTime from rVFC is the PTS time of the frame presented on the video.currentTime timeline, so I guess though ffmpeg has bug mapping seek time for b frames, metadata.mediaTime is reliable since it's generated directly from chrome video player?

**Comment by dalecurtis** [comment]
You can think of requestVideoFrameCallback firing for every frame that gets sent to the compositor when a callback is present. Those frames are sent in presentation order (by timestamp).

I don't know if seeking exactly to the frame timestamp will work properly. It should, but I forget the exact details of how the b-frame bug manifests. Some experiments should let you know.
