### ISSUE TITLE
How is "heavy load on the main thread" defined?

### ISSUE THREAD

**Issue by lincolnneu** [WICG/video-rvfc#65]
> Additionally, if there is a heavy load on the main thread, we might not get a callback for every frame (as measured by a discontinuity in the presentedFrames).

I want to make sure requestVideoFrameCallback is fired when the video is paused or a seek operation succeeds. In the doc it mentions to check the discontinuity of "presentedFrames". But this method requires us to have another fired requestVideoFrameCallback. 
e.g. to know if requestVideoFrameCallback for frame n is fired, we need to know requestVideoFrameCallback for frame n + x is fired (x >= 1). Is it possible to determine if requestVideoFrameCallback is fired without relying on a future requestVideoFrameCallback? Or how can we avoid heavy load on main thread to guarantee requestVideoFrameCallback is called? This is important to us since we plan to rely on requestVideoFrameCallback to determine mediaTime/pts of video frame when the video is paused.

**Comment by tguilbert-google** [comment]
> This is important to us since we plan to rely on requestVideoFrameCallback to determine mediaTime/pts of video frame when the video is paused.

If you pause or seek when paused, the last callback you get should give you the correct mediaTime/PTS.

Heavy load is anything that might be blocking the main JS thread. E.g. doing heavy work in a loop, instead of offloading that work to a worker.

Even if there is no heavy load, you can still miss frames. There is no guarantee that for every frame of a video, a video.rVFC callback will be fired.

**Comment by lincolnneu** [comment]
> If you pause or seek when paused, the last callback you get should give you the correct mediaTime/PTS.

This guarantee is awesome!

**Comment by tguilbert-google** [comment]
> If you pause or seek when paused, the last callback you get should give you the correct mediaTime/PTS.

Update: I was mistaken. There is a chance that you will get newer pixel data if the frame is updated on the compositor thread, after acquiring the frame metadata for video.rVFC. Painting the video to a canvas will always paint the very latest frame, which is good when you're trying to keep a canvas in sync with a video element, but might lead to inaccurate metadata.

When [WebCodecs](https://github.com/WICG/web-codecs) ships, we will consider adding a VideoFrame parameter to rVFC callbacks, to guarantee that the metadata matches the frame.

**Comment by lincolnneu** [comment]
> When WebCodecs ships, we will consider adding a VideoFrame parameter to rVFC callbacks, to guarantee that the metadata matches the frame.

Since chrome 88 stable has launched, do we have an estimated timeline for VideoFrame be included in rVFC callback?

**Comment by tguilbert-google** [comment]
Not really. WebCodecs has to ship 1st (91+), and this would require a spec change. There might also be valid reasons for browsers to not want to make this change, but we haven't really investigated yet.

**Comment by lincolnneu** [comment]
Now that chrome 91 has launched, any updates from rvfc?

**Comment by tguilbert-google** [comment]
WebCodecs is not shipping in 91 or 92. It should (hopefully) in 93 or 94.

It's still not clear that we would add a VideoFrame parameter to rVFC after WebCodecs ships, but I haven't investigated the pros/cons yet.

**Comment by lincolnneu** [comment]
Now webcodecs is shipped in 94. Any updates to add VideoFrame to rVFC?

**Comment by lincolnneu** [comment]
Now it's 96 stable I hope you're considering adding VideoFrame to rVFC. The advantage is rVFC is very easy to use, it'd be a huge improvement if it can easily get video frame accuracy (and thus the existing rVFC users don't need to make breaking change to their codes to use webcodecs). Though I believe there's way to decode the video frame using webcodecs then manage the video frame audio matching to build a "frame accurate video player", it's still a bit complicated if our goal is just to get "which frame number the video player is showing" rather than video editing.
