### ISSUE TITLE
captureTime: present for webrtc use-cases

### ISSUE THREAD

**Issue by fippo** [WICG/video-rvfc#74]
https://wicg.github.io/video-rvfc/#dom-videoframemetadata-capturetime
says it should be present for webrtc use cases. Locally, can that work even? The video element doesn't know a track is going to be sent over a peerconnection.

**Comment by fippo** [comment]
It *can* work for getUserMedia applications which might be what is intended? Happy to do a PR!

**Comment by tguilbert-google** [comment]
I will defer to @drkron to answer this question.

Should the spec be relaxed, or is there an implementation issue (and the capture time should always be present?)

**Comment by fippo** [comment]
i think it is just a wordsmithing issue on the local end.
On the remote end it might be an implementation issue but lets discuss that in the samples pr and maybe a chrome bug

**Comment by drkron** [comment]
I think that the requirement statement is correct for remote sources, but it could be improved for local sources. Phrasing in terms of getUserMedia may be a way to capture that.

Adding @handellm to this thread since he made a change to captureTime recently.
