### ISSUE TITLE
Doubts about `processingDuration` meaning

### ISSUE THREAD

**Issue by philn** [WICG/video-rvfc#79]
https://wicg.github.io/video-rvfc/#dom-videoframemetadata-processingduration

In case some buffering of decoded frames is done before presentation, should this be considered as processing time?

**Comment by dalecurtis** [comment]
No, that wasn't the intent. Processing should take place before buffering for presentation -- it's meant purely to account for decoding time and any color or format processing that takes place before the frame is "at rest"

**Comment by philn** [comment]
Thanks for clearing this up, Dale!
