### ISSUE TITLE
Incorrect mediaTime when stream has packets with a negative PTS

### ISSUE THREAD

**Issue by lincoln-spiteri** [WICG/video-rvfc#80]
If the media file contains a negative start offset on one of the streams, the first callback returns an incorrect media timestamp which has a positive offset and not the PTS of the first video packet. In this case, the first `mediaTime` value becomes a constant error in the `mediaTime` values returned in subsequent callback invocations, therefore the error can be removed to get the correct video frame PTS. This behaviour was observed in Chrome 98. 

The specification does not specify how the browser should behave if the stream contains packets with a negative offset.

```
now: 3853.437, 
playerCallbackMetadata: {
  "expectedDisplayTime":3861.8,
  "height":720,
  "mediaTime":0.021333,
  "presentationTime":3861.8,
  "presentedFrames":1,
  "processingDuration":0.0181,
  "width":1280
}

```

Here is output from `ffprobe` showing the first packets of the file.
 
```
[PACKET]
codec_type=data
stream_index=2
pts=0
pts_time=0.000000
dts=0
dts_time=0.000000
duration=1296000706
duration_time=43200.023533
size=4
pos=47645379
flags=K_
[/PACKET]
[PACKET]
codec_type=audio
stream_index=1
pts=-1024
pts_time=-0.021333
dts=-1024
dts_time=-0.021333
duration=1024
duration_time=0.021333
size=502
pos=47645383
flags=KD
[SIDE_DATA]
side_data_type=Skip Samples
skip_samples=1024
discard_padding=0
skip_reason=0
discard_reason=0
[/SIDE_DATA]
[/PACKET]
[PACKET]
codec_type=video
stream_index=0
pts=0
pts_time=0.000000
dts=0
dts_time=0.000000
duration=1001
duration_time=0.033367
size=22863
pos=47645885
flags=K_
[/PACKET]
[PACKET]
codec_type=audio
stream_index=1
pts=0
pts_time=0.000000
dts=0
dts_time=0.000000
duration=1024
duration_time=0.021333
size=365
pos=47668748
flags=K_
[/PACKET]
[PACKET]
codec_type=audio
stream_index=1
pts=1024
pts_time=0.021333
dts=1024
dts_time=0.021333
duration=1024
duration_time=0.021333
size=323
pos=47669113
```

**Comment by dalecurtis** [comment]
Negative media times are not allowed by the HTML5 video spec.

> In any case, the user agent must ensure that the [earliest possible position](https://www.w3.org/TR/2011/WD-html5-20110113/video.html#earliest-possible-position) (as defined below) using the established [media timeline](https://www.w3.org/TR/2011/WD-html5-20110113/video.html#media-timeline), is greater than or equal to zero.

https://www.w3.org/TR/2011/WD-html5-20110113/video.html#offsets-into-the-media-resource
